# Vos premiers pas en Python
## Ou petit guide de survie ...

Un langage de programmation permet de décrire avec précision des opérations très simples sur des données. Comme tout langage, il a une grammaire et des mot-clés. 
> Un algorithme manipule des données (souvent numériques en calcul scientifique). Ces données ne sont pas connues au moment où on écrit l'algorithme. Les variables servent donc à nommer ces données afin de pouvoir écrire cet algorithme et les stocker en mémoire. 

La procédure de calcul s'articule souvent autour des étapes suivantes:

* On écrit l'algorithme.
* On affecte des valeurs aux variables.
* On exécute l'algorithme de calcul pour obtenir la solution.

Voyons cela quelques usages simples. Il vous suffit d'exécuter chaque petit extrait en appuyant sur le triangle pointant vers la droite dans la barre d'icone ci-dessus ou d'appuyer simultanément sur les touches Shift+Return. N'hésitez pas à modifier les extraits pour mieux comprendre ce que le programme fait.

# Les modules

Les modules sont des extensions du langages comme les "Toolboxes" de Matlab. Python ne sait pas faire grand chose tout seul mais il bénéficie de nombreuses extensions disponibles sous la forme de ces modules. On distingue souvent les extensions présentes lors de l'installation du langage (comme par exemple le module [math](https://docs.python.org/3.4/library/math.html)) ou des extensions tierces qu'il faut installer (comme par exemple l'excellent [numpy](http://www.numpy.org/)).

Pour utiliser une fonctionalité ou fonction d'un module, on utilise l'une des syntaxes suivantes :

In [1]:
import math

print (math.cos(1))

from math import cos
print (cos(2))

from math import * # cette syntaxe est déconseillée car il est possible qu'une fonction
print (cos(3))     # porte le même nom qu'une des vôtres

0.5403023058681398
-0.4161468365471424
-0.9899924966004454


# Les variables

On programme sert souvent à automatiser un calcul comme le calcul mensuel du taux de chômage, le taux d'inflation, le temps qu'il fera demain... Pour pouvoir répéter ce même calcul sur des valeurs différentes, il faut pouvoir décrire ce calcul sans savoir ce que sont ces valeurs. 

Un moyen simple est de les nommer : on utilise des variables. Une variable désigne des données. i=3 signifie que la variable i contient 3. 

Il existe plusieurs types préféfinis de variables, vous trouverez quelques exemples ci-dessous:

In [2]:
i = 3                    # entier = type numérique (type int)
r = 3.3                  # réel   = type numérique (type float)
s = "exemple"            # chaîne de caractères = type str (exemple n'est pas une variable)
n = None                 # None signifie que la variable existe mais qu'elle ne contient rien
                         # elle est souvent utilisée pour signifier qu'il n'y a pas de résultat
                         # car... une erreur s'est produite, il n'y a pas de résultat
                         # (racine carrée de -1 par exemple)
            
print(i,r,s,n)           # avec les notebooks, le dernier print n'est pas nécessaire, il suffit d'écrire
                         # i,r,s,n

3 3.3 exemple None


# Affectations

Lorsqu'on programme, on passe son temps à écrire des calculs à partir de variables pour les stocker dans d'autres variables voire dans les mêmes variables. Lorsqu'on écrit y=x+1, cela veut dire qu'on doit ajouter 1 à x et qu'on stocke le résultat dans y. Lorsqu'on écrit x += 5, cela veut dire qu'on doit ajouter 5 à x et qu'on n'a plus besoin de la valeur que x contenait avant l'opération.

In [3]:
v = "anything"       # affectation
print(v)          # affichage

v1, v2 = 5, 6        # double affectation
print(v1,v2)

x = 2
y = x + 1
print (y)

x += 5              # x = x + 5
print(x)

anything
5 6
3
7


# Mise en forme de l'affichage (`sortie`) avec `print`

In [4]:
titi = "TITI"
gros_minet = "Gros minet"
print("Titi s'apelle",titi)
print(titi + " love " + gros_minet)

x = 4
y = 5 
s = "addition"
print ( "{3} de {0} et {1} donne : {0} + {1} = {2}".format(x,y,x+y,s) )

Titi s'apelle TITI
TITI love Gros minet
addition de 4 et 5 donne : 4 + 5 = 9


# Opérations arithmétiques

In [5]:
x = 5
y = 10

z = x ** y
print (z)    # affiche z

z2 = 5.0/10
print(z2)

z3 = (1+z2**3)/(sqrt(z))
print(z3)

9765625
0.5
0.00036


# Les boucles

Les boucles permettent de répéter un nombre fini ou infini de fois les mêmes instructions. 

** Boucle `for` **

In [6]:
a = 0
print ("La valeur initiale de a est: ", a) 

for i in [10, 1, 4]:
    a = a + i
    print("On ajoute ", i) # répète cette ligne
print ("La valeur finale de a est: ", a)   

La valeur initiale de a est:  0
On ajoute  10
On ajoute  1
On ajoute  4
La valeur finale de a est:  15


In [7]:
for i in range(0, 10) :   # on répète 10 fois
    print ("Dans la boucle",i)     # l'affichage de i
    # ici, on est dans la boucle

# ici, on n'est plus dans la boucle
print("En dehors de la boucle",i)          # on ne passe par à 10

Dans la boucle 0
Dans la boucle 1
Dans la boucle 2
Dans la boucle 3
Dans la boucle 4
Dans la boucle 5
Dans la boucle 6
Dans la boucle 7
Dans la boucle 8
Dans la boucle 9
En dehors de la boucle 9


**Boucle while :**

In [8]:
i = 0
while i < 10 :
    print (i)
    i = i +  1

0
1
2
3
4
5
6
7
8
9


**Interrompre une boucle :**

In [9]:
for i in range (0, 10) : 
    if i == 2 :
        continue           # on passe directement au suivant
    print (i)            
    if i > 5 :
        break              # interruption définitive

0
1
3
4
5
6


# Les tests conditionnels
Les tests permettent de faire un choix : selon la valeur d'une condition, on fait soit une séquence d'instructions soit une autre. 

## Variable de type *boolean*  `True` ou `False`

In [10]:
2 == 2

True

In [11]:
50 == 2*25

True

In [12]:
3 < 3.14159

True

In [13]:
1 == 1.0

True

In [14]:
1 != 0

True

In [15]:
1 <= 2

True

In [16]:
1 >= 1

True

## Le test `if`

In [17]:
a = 10
if a > 0 :
      print(a)     # un seul des deux blocs est pris en considération

10


## Le test `if ... else`

In [18]:
v = 3
if v == 2 :
    print ("v est égal à 2")
else :
    print ("v n'est pas égal à 2")

v n'est pas égal à 2


**La clause ``else`` n'est obligatoire :**

In [19]:
v = 2
if v == 2 :
    print ("v est égal à 2")

v est égal à 2


## Plusieurs tests enchaînés : `if ... elif ... else`

In [20]:
v = 0
if v == 2 :
    print ("v est égal à 2")
elif v > 2 :
    print ("v est supérieur strictement à 2")
else :
    print ("v est inférieur à 2")

v est inférieur à 2


# Les chaînes de caractères (type `str`)

In [21]:
a = 10
print(a)     # quelle est la différence
print("a")   # entre les deux lignes
s = "texte"
s = "c" + " " + s +" " + "c"
print(s)

10
a
c texte c


Toute valeur a un type et cela détermine les opérations qu'on peut faire dessus. ``2 + 2`` fait ``4`` pour tout le monde. ``2 + "2"`` fait quatre pour un humain, mais est incompréhensible pour l'ordinateur car on ajoute deux choses différentes (``torchon + serviette``).

In [22]:
print("2" + "3")
print(2+3)

23
5


# Les fonctions

Les fonctions sont des portions de programmes qui reproduisent les mêmes instructions. La fonction suivante calcule un polynôme de second degré $x^2+x-5$. 

A chaque fois qu'on appellera la fonction ``polynome``, elle fera le même calcul sur des ``x`` différents. Cela évite principalement d'avoir à recopier les mêmes lignes à chaque fois qu'on en a besoin.

In [23]:
def polynome( x=1 ) :
    return x**2 + x - 5

polynome()

-3

Une fonction commence toujours par ``def``. Entre parenthèses, ce sont les paramètres (ou entrées de la fonction). Ce qui suit le mot-clé ``return`` est le résultat de la fonction (ou sa sortie). Parmi les fonctions, il y a celles qui existent déjà et celles que vous écrivez. La fonction ``cos`` existe déjà : elle fait un calcul qu'il n'est pas besoin de réécrire. La fonction ``polynome`` décrite plus haut n'existait pas avant de l'avoir définie.

On peut appeler une fonction depuis une autre fonction. Une fonction peut prendre autant de paramètres que l'on veut à condition qu'ils aient des noms différents. On peut aussi leur associer une valeur par défaut :

In [24]:
from math import log  # on importe une fonction existante
def log_base ( x, base = 10 ) :
    return log (x) / log(base)

y = log_base (1000)      # identique à y = log_base (1000, 10)
z = log_base (1000, 2)   # logarithme en base deux
y,z

(2.9999999999999996, 9.965784284662087)

# Numpy et Scipy

[Numpy](http://numpy.org) contient des routines de base pour effectuer des opérations vectorielles, matricielles et algébriques linéaires rapides en Python. [Scipy](http://scipy) contient des routines supplémentaires pour l'optimisation, des fonctions spéciales, etc. Les deux contiennent des modules écrits en C et Fortran afin qu'ils soient aussi rapides que possible. Ensemble, ils donnent à Python à peu près la même capacité que le programme  [Matlab](http://www.mathworks.com/products/matlab/). En fait, si vous êtes un utilisateur expérimenté de Matlab, il existe un [guide to Numpy for Matlab users](http://www.scipy.org/NumPy_for_Matlab_Users)

## Création de vecteurs et matrices

La capacité de travailler avec des vecteurs et des matrices est fondamental à la fois à Numpy et Scipy. Vous pouvez créer des vecteurs à partir de listes à l'aide de la commande `array`:

In [25]:
# On charge le module pylab. 
# L'environnement de travail pylab offre une syntaxe proche de Matlab et permet une prise en main rapide
from pylab import * 

In [26]:
# Vecteur v à 6 éléments
v = array([0,1,2,3,4,5])

print(v)       # On affiche le vecteur
print(v.shape) # On affiche sa forme
print(v.size) # On affiche sa taille

print(v[0])    # On affiche le premier élement du tableau, l'indextation commence à 0
print(v[-1])   # On affiche le dermier élement du tableau
print(v[1:4])  # On affiche du 2ème au 4ème éléments, le 5ème n'est pas pris en compte
print(v[0:-1:2]) # On affiche un élément sur 2
print(v[:])    # On affiche tout le vecteur
print(v[-1:0:-1]) # On renverse the vecteur


print(max(v))  # On affiche le max de ses valeurs
print(min(v))  # On affiche le min de ses valeurs
print(mean(v)) # On affiche la moyenne de ses valeurs
print(v[v>=2])  # On affiche que les éléments >= 2
v[2] = 1.5
print(v[v>=2])  # On affiche que les éléments >= 2


[0 1 2 3 4 5]
(6,)
6
0
5
[1 2 3]
[0 2 4]
[0 1 2 3 4 5]
[5 4 3 2 1]
5
0
2.5
[2 3 4 5]
[3 4 5]


In [27]:
# Matrice A 2x4
A = array([[0, 1, 2, 3],
           [4, 5, 6, 7]])

print(A)       # On affiche la matrice
print(A.shape) # On affiche sa forme
print(A.size)  # On affiche sa taille

print(A[1,:])   # On affiche la 2ème ligne, toutes les colonnes
print(A[:,1])   # On affiche la 2ème colonne, toutes les lignes
print(A[1,1:4]) # On affiche du 2ème au 4ème éléments de la seconde ligne

print(max(A[1,:]))  # On affiche le max de la deuxième ligne
print(max(A[:,1]))  # On affiche le max de la deuxième colonne
print(A.max())  # On affiche le max de la matrice

A[1,2] = 8
print(A.max())  # On affiche le max de la matrice
A[0,:] = [9, 10, 11, 12] # On affecte la première ligne
print(A)
print(A.max())  # On affiche le max de la matrice

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
8
[4 5 6 7]
[1 5]
[5 6 7]
7
5
7
8
[[ 9 10 11 12]
 [ 4  5  8  7]]
12


### Vecteurs et matrices nuls

Vous pouvez également former des matrices vides (zéro) de forme arbitraire (y compris les vecteurs, que Numpy traite comme des vecteurs avec une ligne), en utilisant la commande `zeros`:

In [28]:
Nx = 3
v = zeros(Nx)
print(v)

[0. 0. 0.]


In [29]:
Nx = 3
Nt = 2
c = zeros((Nx,Nt))
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Distribution de valeurs avec `linspace` 

La commande `linspace` construit un tableau linéaire de points d'une valeur de départ à une valeur de fin avec un nombre spécifique de points.

In [30]:
start     = 0
stop      = 1
nb_points = 5

x = linspace(start,stop,nb_points)
print(x)

[0.   0.25 0.5  0.75 1.  ]


### Distribution de valeurs avec `arange` 

La commande `arange` construit un tableau linéaire de points d'une valeur de départ à une valeur de fin avec un pas spécifique.

In [31]:
start = 0
stop  = 1
step  = 0.25

x = arange(start,stop,step)
print(x)

[0.   0.25 0.5  0.75]


**Que remarquez-vous ?**

# Figures avec Matplotlib

In [32]:
# L'environnement de travail pylab offre une syntaxe proche de Matlab et permet une prise en main rapide
# nbagg est une option permet d'avoir des graphiques interactifs dans le notebook
%pylab nbagg

Populating the interactive namespace from numpy and matplotlib


/home/fbob/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['linalg', 'power', 'step', 'random', 'fft']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [33]:
start     = 0
stop      = 2*pi
nb_points = 25
x = linspace(start,stop,nb_points)

In [34]:
figure()
title("Titre de la figure")

plot(x,sin(x),'b-',label='sin(x)',linewidth=1)
plot(x,cos(x),'ro-',label='cos(x)',linewidth=3)

ylabel("Concentration $c(x,t)$")
xlabel("Abscisse $x$ des noeuds")

grid()
legend()

<IPython.core.display.Javascript object>

**Un exemple d'utilisation des widgets**

In [35]:
import ipywidgets as widgets
from IPython.display import display
from pylab import * 

%matplotlib nbagg

In [36]:
x = linspace(0, 2, 1000)
fig, ax = subplots(1, figsize=(10, 4))
suptitle('Onde sinusoidale')


def update_plot(amp, phase, freq):
    
    ax.clear()
    y = amp * np.sin(freq * 2 * np.pi * x + phase * 2 * np.pi)
    units = 'amp = {} $(psi)$ \nphase = {} $(s)$ \nfreq = {} $(Hz)$'
    
    ax.plot(x, y, label=units.format(amp, phase, freq))
    ax.set_xlim(x[0], x[-1])
    ax.legend(loc="upper right")
    ax.set_xlabel('$(s)$')
    show()


amp = widgets.FloatSlider(min=1, max=10, value=1, description='Amp:')
phase = widgets.FloatSlider(min=0, max=5, value=0, description='Phase:')
freq = widgets.FloatSlider(min=1, max=10, value=1, description='Freq:')
    
widgets.interactive(update_plot, amp=amp, phase=phase, freq=freq)

<IPython.core.display.Javascript object>

interactive(children=(FloatSlider(value=1.0, description='Amp:', max=10.0, min=1.0), FloatSlider(value=0.0, de…